name: Custom Scheduled Push

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "gabrielecanova99@gmail.com"
          git config --global user.name "Gugor99"

      # Get the current day of the week (1=Monday, 7=Sunday)
      - name: Get current day of the week
        run: echo "DAY_OF_WEEK=$(date +%u)" >> $GITHUB_ENV

      # Get the custom week number, cycling every 25 weeks from the publication date (2024-10-24)
      - name: Get current week number
        id: week
        run: |
          PUB_DATE=$(date -d "2024-10-21" +%s)
          CURRENT_DATE=$(date +%s)
          WEEK_NUMBER=$(( ((CURRENT_DATE - PUB_DATE) / 604800 % 25) + 1 ))
          echo "WEEK_NUMBER=$WEEK_NUMBER" >> $GITHUB_ENV

      # Determine if today is a commit day based on the custom schedule
      - name: Check commit schedule
        id: schedule
        run: |
          # Define the custom schedule for each week
          # Use days of the week (1=Monday, 7=Sunday) for each week
          SCHEDULE=(
            "7"                     # Week 1: Sunday
            "1 2 3 4 5 6"           # Week 2: Monday to Saturday
            "3 7"                   # Week 3: Tuesday and Sunday
            "1 2 3 4 5 6"           # Week 4: Monday to Saturday
            "5"                     # Week 5: Thursday
            "1 2 3 4 5 6"           # Week 6: Monday to Saturday
            "7"                     # Week 7: Sunday
            "1 2 3 4 5 6 7"         # Week 8: Every day
            "3"                     # Week 9: Tuesday
            "1 2 4 5 6"             # Week 10: Mon, Tue, Thu, Fri, Sat
            "7"                     # Week 11: Sunday
            "1 2 3 4 5 6 7"         # Week 12: Every day
            "3 6 7"                 # Week 13: Tue, Sat, Sun
            "6"                     # Week 14: Saturday
            ""                      # Week 15: No commit days
            "7"                     # Week 16: Sunday
            "1 2 3 4 5 6"           # Week 17: Monday to Saturday
            "1"                     # Week 18: Monday
            "2"                     # Week 19: Tuesday
            "1 7"                   # Week 20: Monday and Sunday
            "1 2 3 4 5 6"           # Week 21: Monday to Saturday
            "7"                     # Week 22: Sunday
            "1 2 3 4 5 6 7"         # Week 23: Every day
            "3 6 7"                 # Week 24: Tue, Sat, Sun
            "6"                     # Week 25: Saturday
          )
          # Get current week's schedule
          WEEK_SCHEDULE="${SCHEDULE[$(($WEEK_NUMBER - 1))]}"
          # Check if today is a commit day
          if [[ "$WEEK_SCHEDULE" =~ $DAY_OF_WEEK ]]; then
            echo "COMMIT=true" >> $GITHUB_ENV
          else
            echo "COMMIT=false" >> $GITHUB_ENV
          fi

      # Commit and push if today is a commit day
      - name: Make a commit
        if: env.COMMIT == 'true'
        run: |
          git commit --allow-empty -m "Scheduled commit for week ${{ steps.week.outputs.WEEK_NUMBER }} on day ${{ env.DAY_OF_WEEK }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
